CREATE TABLE `users` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`gro_id` VARCHAR(50) NULL DEFAULT '0',
	`fname` VARCHAR(50) NULL DEFAULT '0',
	`lname` VARCHAR(50) NULL DEFAULT '0',
	`username` VARCHAR(50) NULL DEFAULT '0',
	`password` VARCHAR(50) NULL DEFAULT '0',
	`create_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`status` ENUM('1','0') NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=3
;
