CREATE TABLE `tbl_dow` (
	`dow_id` INT(11) NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(250) NULL DEFAULT NULL,
	`dow_discount` VARCHAR(250) NULL DEFAULT NULL,
	`dow_img` VARCHAR(250) NULL DEFAULT NULL,
	`dow_name` VARCHAR(250) NULL DEFAULT NULL,
	`dow_brand_name` VARCHAR(250) NULL DEFAULT NULL,
	`dow_price` VARCHAR(250) NULL DEFAULT NULL,
	`dow_available` VARCHAR(250) NULL DEFAULT NULL,
	`dow_sold` VARCHAR(250) NULL DEFAULT NULL,
	`dow_timer` VARCHAR(250) NULL DEFAULT NULL,
	`dow_old_price` VARCHAR(250) NULL DEFAULT NULL,
	`dow_best_price` VARCHAR(250) NULL DEFAULT NULL,
	`dow_hours` VARCHAR(250) NULL DEFAULT NULL,
	`dow_mins` VARCHAR(250) NULL DEFAULT NULL,
	`dow_secs` VARCHAR(250) NULL DEFAULT NULL,
	PRIMARY KEY (`dow_id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=8
;
